"""Render judged findings to markdown + the structured JSON the eval reads."""

from __future__ import annotations

import json
from datetime import date

from security_agent.findings import Finding

_VERDICT_MARK = {
    "false_positive": "FP",
    "expected_by_design": "OK",
    "true_positive": "**TP**",
}


def render_markdown(
    findings: list[Finding],
    sut: str,
    model: str | None,
    today: date | None = None,
) -> str:
    today = today or date.today()
    n = len(findings)
    tp = sum(1 for f in findings if f.verdict == "true_positive")
    fp = sum(1 for f in findings if f.verdict == "false_positive")
    exp = sum(1 for f in findings if f.verdict == "expected_by_design")

    out: list[str] = []
    out.append("# Security agent — finding triage")
    out.append("")
    out.append(f"_Run: {today.isoformat()}_  •  SUT: `{sut}`  •  judge: `{model or 'none (heuristic only)'}`")
    out.append("")
    out.append(
        f"{n} finding(s) judged — **{tp} true-positive**, {fp} false-positive, "
        f"{exp} expected-by-design. True positives carry a disposition + register cross-reference; "
        "noise is explained, not silently dropped."
    )
    out.append("")

    out.append("## Summary")
    out.append("")
    out.append("| Finding | Kind | Verdict | Disposition | Risk |")
    out.append("|---|---|---|---|---|")
    for f in findings:
        v = _VERDICT_MARK.get(f.verdict, f.verdict or "—")
        out.append(
            f"| `{f.rule_id}` {f.location} | {f.kind} | {v} | {f.disposition or '—'} | {f.candidate_risk_id or '—'} |"
        )
    out.append("")

    out.append("## Findings")
    out.append("")
    for f in findings:
        out.append(f"### `{f.rule_id}` — {f.location}")
        out.append("")
        out.append(
            f"- **tool:** {f.tool} ({f.kind})  •  **severity:** {f.severity}"
            f"{' / conf ' + f.confidence if f.confidence else ''}"
        )
        out.append(f"- **title:** {f.title}")
        out.append(
            f"- **verdict:** `{f.verdict or '—'}`  •  **disposition:** `{f.disposition or '—'}`"
            f"  •  **risk:** {f.candidate_risk_id or 'none'}"
        )
        if f.rationale:
            out.append(f"- **rationale:** {f.rationale}")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        "_Generated by `security_agent.run` (B1c). The deterministic scanners in "
        "[`nonfunctional/security/`](../../nonfunctional/security/) detect; this agent judges. "
        "Advisory — a starting point for the reviewer, not a gate._"
    )
    out.append("")
    return "\n".join(out)


def to_json(findings: list[Finding]) -> str:
    return json.dumps(
        [
            {
                "signature": list(f.signature),
                "tool": f.tool,
                "kind": f.kind,
                "rule_id": f.rule_id,
                "location": f.location,
                "severity": f.severity,
                "confidence": f.confidence,
                "title": f.title,
                "verdict": f.verdict,
                "disposition": f.disposition,
                "candidate_risk_id": f.candidate_risk_id,
                "rationale": f.rationale,
            }
            for f in findings
        ],
        indent=2,
    )
