"""Render triage clusters to markdown."""

from __future__ import annotations

from datetime import UTC, date, datetime

from triage_agent.cluster import Cluster


def render_markdown(
    clusters: list[Cluster],
    repo: str,
    since_days: int,
    total_runs_scanned: int,
    today: date | None = None,
    model: str | None = None,
) -> str:
    today = today or date.today()
    total_failures = sum(len(c.members) for c in clusters)
    lines: list[str] = []
    lines.append(f"# CI failure triage — {repo}")
    lines.append("")
    cutoff = today.isoformat()
    meta = [f"_Run: {cutoff} • window: last {since_days} days • model: `{model or '—'}`_"]
    lines.append("  \n".join(meta))
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    if not clusters:
        lines.append("_No failures in the configured window. Nothing to triage._")
        lines.append("")
        return "\n".join(lines)
    lines.append(
        f"Scanned {total_runs_scanned} failed run(s) in the window; extracted {total_failures} "
        f"failure(s); clustered into **{len(clusters)} group(s)** by `(test path, test name, error class)`."
    )
    lines.append("")

    # Sparkline-ish table for quick scan
    lines.append("| # | Cluster signature | Members | Category | R-ID |")
    lines.append("|---|---|---|---|---|")
    for i, c in enumerate(clusters, start=1):
        path, name, err = c.signature
        sig = f"`{path}::{name}` → `{err}`" if path != "<step>" else f"`{name}` → `{err}`"
        rid = c.candidate_risk_id or "—"
        lines.append(f"| {i} | {sig} | {len(c.members)} | {c.category or '—'} | {rid} |")
    lines.append("")

    lines.append("## Clusters")
    lines.append("")
    for i, c in enumerate(clusters, start=1):
        path, name, err = c.signature
        lines.append(f"### {i}. {name} — `{err}`")
        lines.append("")
        if path != "<step>":
            lines.append(f"**Test path:** `{path}`")
            lines.append("")
        rid = (
            f"**Candidate risk:** `{c.candidate_risk_id}`"
            if c.candidate_risk_id
            else "**Candidate risk:** _none in register_"
        )
        lines.append(f"**Category:** `{c.category or 'unknown'}` • {rid}")
        lines.append("")
        if c.rationale:
            lines.append(f"**Why:** {c.rationale}")
            lines.append("")
        if c.suggested_action:
            lines.append(f"**Action:** {c.suggested_action}")
            lines.append("")
        lines.append(f"**Members ({len(c.members)}):**")
        lines.append("")
        for m in sorted(c.members, key=lambda x: x.run.created_at, reverse=True):
            r = m.run
            when = r.created_at.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")
            line = f"- [run #{r.number}]({r.url}) — {when} — `{r.event}` on `{r.branch}` @ `{r.sha[:7]}` — {r.title}"
            lines.append(line)
        lines.append("")
        # Representative error message
        f = c.members[0].failure
        lines.append(f"**Representative error:** `{f.error_message}`")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by `triage_agent` (phase 10). Advisory — clusters are a starting point for "
        "the on-call reviewer, not a categorisation gate. See [`triage_agent/README.md`](../README.md)._"
    )
    lines.append("")
    return "\n".join(lines)


def _now_utc() -> datetime:
    return datetime.now(UTC)
