"""Render the agent's structured result to markdown for the evidence artefact."""

from __future__ import annotations

from datetime import date

from risk_agent.agent import AgentResult
from risk_agent.diff import DiffBundle


def render_markdown(result: AgentResult, diff: DiffBundle, today: date | None = None) -> str:
    today = today or date.today()
    lines: list[str] = []
    title_parts = ["# Risk-prioritised test plan"]
    if diff.pr_number is not None:
        title_parts.append(f"— PR #{diff.pr_number}")
    lines.append(" ".join(title_parts))
    lines.append("")
    if diff.title:
        lines.append(f"**{diff.title}**")
        lines.append("")
    meta = [f"_Run: {today.isoformat()} • model: `{result.model}`_"]
    if diff.repo:
        meta.append(f"_Repo: {diff.repo}_")
    if diff.truncated:
        meta.append(f"_Diff truncated for prompt size ({diff.total_lines} total lines in source diff)._")
    lines.append("  \n".join(meta))
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(result.summary)
    lines.append("")

    lines.append("## Changed files")
    lines.append("")
    if diff.files:
        for f in diff.files:
            lines.append(f"- `{f}`")
    else:
        lines.append("_(no files detected in diff)_")
    lines.append("")

    lines.append("## Ranked risks")
    lines.append("")
    if not result.ranked_risks:
        lines.append("_The agent did not raise any register risks for this diff._")
        lines.append("")
    for i, r in enumerate(result.ranked_risks, start=1):
        gap = " — **COVERAGE GAP**" if r.get("is_gap") else ""
        rel = {3: "direct", 2: "plausible"}.get(r.get("relevance", 0), str(r.get("relevance")))
        lines.append(f"### {i}. {r['id']} — _{rel}_{gap}")
        lines.append("")
        lines.append(f"**Why:** {r['rationale']}")
        lines.append("")
        lines.append(f"**Covered by:** {r['covered_by']}")
        lines.append("")
        lines.append(f"**Action:** {r['action']}")
        lines.append("")

    lines.append("## Exploratory probes")
    lines.append("")
    if result.exploratory_probes:
        for p in result.exploratory_probes:
            lines.append(f"- {p}")
    else:
        lines.append("_(none suggested)_")
    lines.append("")

    # Phase 13 v1 audit: surface what the deterministic pre-filter excluded
    # before the LLM saw the register. A human reviewer can sanity-check
    # whether any filtered row should plausibly have been raised, which is
    # the v1 mitigation for hand-authored-mapping false negatives.
    if result.prefilter_fallback_used:
        lines.append("## Pre-filter")
        lines.append("")
        lines.append(
            "_The pre-filter found no file-path match for any mapped pattern in this "
            "diff; the full register was sent to the agent. (See `risk_agent/prefilter.py`.)_"
        )
        lines.append("")
    elif result.filtered_out_ids:
        lines.append("## Pre-filter")
        lines.append("")
        lines.append(
            "_Filtered out by the deterministic pre-filter before the LLM saw the register "
            "(no file-path mapping intersects the diff). If a reviewer thinks a row below "
            "should have been raised, sharpen its patterns in `risk_agent/prefilter.py`._"
        )
        lines.append("")
        for rid in result.filtered_out_ids:
            lines.append(f"- {rid}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by `risk_agent` (phase 13). This is an advisory plan for a human "
        "reviewer; it is not a CI gate. See [`risk_agent/README.md`](../README.md)._"
    )
    lines.append("")
    return "\n".join(lines)
