"""Render probe results + findings to markdown and JSON."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date

from explore_agent.judge import Finding
from explore_agent.probe import Probe


@dataclass
class Result:
    probe: Probe
    finding: Finding


_SEVERITY_RANK = {"high": 0, "med": 1, "low": 2}
_CATEGORY_RANK = {
    "auth_boundary_concern": 0,
    "unexpected_5xx": 1,
    "business_rule_concern": 2,
    "schema_drift": 3,
    "documented_public_endpoint": 4,
    "expected": 5,
}


def _sort_key(r: Result) -> tuple[int, int, str]:
    return (
        _CATEGORY_RANK.get(r.finding.category, 99),
        _SEVERITY_RANK.get(r.finding.severity, 99),
        r.probe.endpoint.signature,
    )


def render_markdown(
    results: list[Result],
    base_url: str,
    model: str,
    today: date | None = None,
) -> str:
    today = today or date.today()
    lines: list[str] = []
    lines.append("# Exploratory probe — golf-web-app API")
    lines.append("")
    lines.append(f"_Run: {today.isoformat()} • base url: `{base_url}` • model: `{model}`_")
    lines.append("")

    if not results:
        lines.append("_No probes ran. Check the SUT is up at the configured base url._")
        return "\n".join(lines)

    by_cat: dict[str, int] = {}
    for r in results:
        by_cat[r.finding.category] = by_cat.get(r.finding.category, 0) + 1

    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"Sent **{len(results)}** probe(s) across "
        f"**{len({r.probe.endpoint.signature for r in results})}** endpoint(s). "
        "Findings (LLM-classified, advisory):"
    )
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for cat in (
        "auth_boundary_concern",
        "unexpected_5xx",
        "business_rule_concern",
        "schema_drift",
        "documented_public_endpoint",
        "expected",
    ):
        if cat in by_cat:
            lines.append(f"| `{cat}` | {by_cat[cat]} |")
    lines.append("")

    sorted_results = sorted(results, key=_sort_key)

    lines.append("## Findings")
    lines.append("")
    lines.append("| # | Endpoint | Variant | Auth | Status | Category | Severity |")
    lines.append("|---|---|---|---|---|---|---|")
    for i, r in enumerate(sorted_results, start=1):
        sev = r.finding.severity if r.finding.category not in ("expected", "documented_public_endpoint") else "—"
        lines.append(
            f"| {i} | `{r.probe.endpoint.signature}` | `{r.probe.variant.label}` | "
            f"`{r.probe.auth_mode}` | "
            f"{r.probe.status} | `{r.finding.category}` | {sev} |"
        )
    lines.append("")

    lines.append("## Detail")
    lines.append("")
    for i, r in enumerate(sorted_results, start=1):
        ep = r.probe.endpoint
        lines.append(f"### {i}. `{ep.signature}` — {r.probe.variant.label}")
        lines.append("")
        lines.append(f"**Category:** `{r.finding.category}`")
        if r.finding.category not in ("expected", "documented_public_endpoint"):
            lines.append(f"  **Severity:** `{r.finding.severity}`")
        lines.append("")
        lines.append(f"**Auth mode:** `{r.probe.auth_mode}`")
        lines.append("")
        lines.append(f"**Variant rationale:** {r.probe.variant.rationale}")
        lines.append("")
        lines.append(f"**Finding rationale:** {r.finding.rationale}")
        lines.append("")
        lines.append(
            f"**HTTP:** `{r.probe.request_method} {r.probe.request_url}` → "
            f"`{r.probe.status}` in `{r.probe.latency_ms:.0f} ms`"
        )
        lines.append("")
        if r.probe.request_body is not None:
            body_blob = json.dumps(r.probe.request_body, indent=2)
            if len(body_blob) > 400:
                body_blob = body_blob[:400] + "\n... (truncated)"
            lines.append("Request body:")
            lines.append("```json")
            lines.append(body_blob)
            lines.append("```")
            lines.append("")
        resp_blob = r.probe.response_text[:400]
        if len(r.probe.response_text) > 400:
            resp_blob += "\n... (truncated)"
        lines.append("Response (first 400 chars):")
        lines.append("```")
        lines.append(resp_blob)
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by `explore_agent` (phase 12 v1 v1). Advisory — findings are a "
        "starting point for a reviewer, not a gate. See [`explore_agent/README.md`]"
        "(../README.md)._"
    )
    lines.append("")
    return "\n".join(lines)


def to_json(results: list[Result]) -> str:
    """JSON dump suitable for diffing across runs or feeding downstream agents."""
    out = []
    for r in results:
        out.append(
            {
                "endpoint": {
                    "method": r.probe.endpoint.method,
                    "path": r.probe.endpoint.path,
                    "summary": r.probe.endpoint.summary,
                },
                "variant": {
                    "label": r.probe.variant.label,
                    "body": r.probe.variant.body,
                    "rationale": r.probe.variant.rationale,
                },
                "http": {
                    "method": r.probe.request_method,
                    "url": r.probe.request_url,
                    "status": r.probe.status,
                    "latency_ms": round(r.probe.latency_ms, 2),
                    "response_text_truncated": r.probe.response_text[:1000],
                },
                "auth_mode": r.probe.auth_mode,
                "finding": {
                    "category": r.finding.category,
                    "severity": r.finding.severity,
                    "rationale": r.finding.rationale,
                },
            }
        )
    return json.dumps(out, indent=2)
